### ISSUE TITLE
Randomly choose between multiple messages?

### ISSUE THREAD

**Issue by Bionic-Dog** [LordVGames/ConfigurableProgMsgs#1]
Could be funny, though I understand if it would be too much to code. I think the variance would keep things a little more interesting.

**Comment by LordVGames** [comment]
I'm thinking it shouldn't be too bad to make, so I'll see what I can do.

**Comment by LordVGames** [comment]
Just added in version 2.0.0! Split each message with `EXTRAMSG:` and the game will randomly pick one each time.
