### ISSUE TITLE
send on stage x changing

### ISSUE THREAD

**Issue by AWB0** [LordVGames/ConfigurableProgMsgs#2]
whenever i go to the stage with the message send on stage x goes down one stage for some reason, after some time all the messages just don't get sent because they'll go to -1, the options for sending messages on loops or specific stages work perfectly though.

**Comment by LordVGames** [comment]
yep i found the problem, it might also have been changing the config value itself 
will be fixed next update

**Comment by LordVGames** [comment]
should be fixed as of 2.1.0
